### ISSUE TITLE
No info for `raw_data`

### ISSUE THREAD

**Issue by thetarnav** [DanielGavin/ols#922]
```odin
s: []int
m := raw_data(s)

// no hover info for `m` nor `raw_data`

// should be
// m: [^]int
// raw_data :: proc(value: []int) -> [^]int
```

`raw_data` appears in autocompletions, and it is defined in ols builtin.odin:
https://github.com/DanielGavin/ols/blob/52839df5fa441be5cf1cd0fb0e6b43cb5c6560c6/builtin/builtin.odin#L39-L45

**Comment by BradLewis** [comment]
I've merged in a fix for this but it did require changing how we handle private symbols. Let me know if you run into any issues where you have things like completions that shouldn't be there, or completions that are missing.

**Comment by monkoose** [comment]
@BradLewis Is this fixed?
I can't get info for raw_data, nor references for an identifier.

As example you can't get `data_ptr` references, nor jump to definition and hover information. If you explicitly add type for it as `[^]u8` then it works.
`raw_data` still doesn't show any hover information.

Note: I'm using ols(latest commit) with neovim editor.

```odin
package main

import "core:fmt"

main :: proc() {
    data: [512]u8
    data[0] = '!'
    data_ptr := raw_data(data[:])
    fmt.printfln("%q", cstring(data_ptr))
}
```

**Comment by BradLewis** [comment]
It works fine for me:

<img width="1408" height="262" alt="Image" src="https://github.com/user-attachments/assets/0184caad-69e7-457d-9403-6023b3eb2248" />

It might be an issue with looking for builtin procs, do you get completions and everything for other builtins? If it's not, you need to make sure the `builtin` folder that's in the repo is next to the built executable so it can find the builtin procs. If this is the case there should also be a log in your `LspLog`.

I also realised that I don't think that's actually documented in the readme so I'll be sure it add it as well.

**Comment by monkoose** [comment]
Thank you. I'm away from my PC right now, so will check it later. But I guess it is the case, I have built Odin from sources and don't remember that I placed builtin dir near the odin executable

**Comment by monkoose** [comment]
Finally got time to check this.
I have `base/builtin` at the same path as `odin` executable.
I'm on linux and I'm checked that distro's package install only copies `base`, `core`, `shared` and `vendor` dirs at the same location as the executable.
Aren't it should be like so?

I do see lsp warnings in the logs as you mentioned. I have explicitly copied `builtin` directory to the same dir. Warnings are gone, but I still don't get hover info, references for this case. Does `builtin` dir should only have `builtin.odin` file?

**Comment by monkoose** [comment]
Oh wait I got it, I should copy `builtin` directory from this repo, not from odin.
After doing so all works fine.

Thank You for the help.
